### ISSUE TITLE
Return value of delete_user($username)

### ISSUE THREAD

**Issue by iwashi** [fuel/auth#85] opened 2014-07-08 10:05 UTC
According to function comment as below, delete_user($username) should return boolean value.

https://github.com/fuel/auth/blob/61e3c14e9a5bd325e1f41f46b1e10e99504342b1/classes/auth/login/ormauth.php#L481

However, it seems that delete user($username) returns "Model  this instance as a new object without primary key(s)" shown as below:

https://github.com/fuel/orm/blob/e8457ba9296078310cdea47002e5c7b7cb083da2/classes/model.php#L1456

I think that delete_user($username) should return boolean value as documented.

**Comment by WanWizard** [comment] 2014-07-08 15:23
Duplicate of #86

**Closed as completed by WanWizard** 2014-07-08 15:23 UTC
